dist: focal
service_name: travis-pro
repo_token: process.env.COVERALLS_REPO_TOKEN
language: node_js
node_js:
- "14.17.0"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
before_deploy:
  - mv .gitignore.prod .gitignore
deploy:
  provider: azure_web_apps
  on:
    all_branches: false

notifications:
  email: false
