dist: focal
language: node_js
node_js:
- "14.17.0"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm run test-on-travis
deploy:
  provider: azure_web_apps
  on:
    all_branches: false

notifications:
  email: false
