
language: node_js
os: "linux"
dist: "focal"  
branches:
  only:
  - master
node_js:
- "14.17.0"
cache:
  directories:
    - node_modules
install:
- npm install
script:
- npm run test-on-travis
before_deploy:
  - git add . 
  - git commit -m 'Travis'
deploy:
  provider: azure_web_apps
  on:
    branch: master
